### PR TITLE
feature/victoryIcons: building on develop branch

### PR DESCRIPTION
**Pull request by sudo-saksham**
User can now add Victory Icons when they register a victory. This version is build on top of ```develop``` branch and hence doesn't have Twitter Authentication implemented.

### CODE REVIEW

**Comment by ScottishRoss** [comment]
That's better! I was just replying to you on your other PR. I'll clone and check out your PR tomorrow when I have some time.

**Comment by sudo-saksham** [comment]
Okay, also can you review the Facebook sign-in PR by tomorrow EOD? I'll make the PR within 10 hours.

**Comment by ScottishRoss** [comment]
I promise to review by EOD tomorrow, I want to make sure you get your Hacktoberfest credit.

**Comment by sudo-saksham** [comment]
Also, Can you make a branch in your repo for the Facebook login feature like you made for Twitter? I'll make the PR in that branch itself so that it won't interrupt the flow of other feature.

**Comment by ScottishRoss** [comment]
Tagged as accepted. Will review in more detail later.

**Comment by sudo-saksham** [comment]
This is the merge request where the user is deleted in the firebase. I'll set up the whole state management for this app and update the UI later. @ScottishRoss

**Pull request closed without merging**
